### ISSUE TITLE
As a programmer I don't want to make a new selection screen for every option path

### ISSUE THREAD

**Issue by Oway5** [OmarD-Dev/FoodInspectorParadise#10]
As a programmer, I should have some way of generating a functional selection screen that can swap from chips to drinks to bread choice. This should be able to generate based on an input of choices.

**Comment by ScripttKitty** [comment]
The interfaces we made are based on CLI functions. Where the user is met with a screen of options and they type in the number of their choice.

                                       1. Add bread
                                       2. Add toppings
                                       3. Add chips
                                       4. Add drink
                                       5. Go back
 
This example extends to all the other interfaces that we have, allowing the user to move freely throughout the application.
