### ISSUE TITLE
Create a Receipt File for each Order

### ISSUE THREAD

**Issue by OmarD-Dev** [OmarD-Dev/FoodInspectorParadise#11]
As a programmer, I want to be able to have a receipt file for each order to allow for better organization and readability.

**Comment by ScripttKitty** [comment]
To achieve this, we will be implementing a csv file to save all of our receipts. Addititonally, we'll be using "|" symbol as a delimiter and a buffered reader and writer to store information onto our file.

Every file will be named as follows:

**yyyyMMdd-hhmmss.txt**

**Comment by ScripttKitty** [comment]
Sandwich - Size: 8, Cost: $10.80, Toasted: true, BreadType: White, Regular Toppings: Ketchup, Ketchup,  Premium Toppings: Roast Beef, American- $10.8
Drink - Type: PEPSI, Size: MEDIUM, 2.50- $2.5
Chips - Flavor: CHEETOS, Cost- $1.5
Total: $ 14.8
