### ISSUE TITLE
As a user I would like to be able to customize my sandwich to add to my order

### ISSUE THREAD

**Issue by Oway5** [OmarD-Dev/FoodInspectorParadise#3]

**Comment by Oway5** [comment]
The user may customize the sandwhich after opening its respective menu. They may also leave the menu.

**Comment by ScripttKitty** [comment]
For this feature, we will have let the user choose their sandwich size, bread type, and toppings. Depending on their selections, a relevent menu screen will open and display choices for them. 

             1: Add Sandwich
             2: Add Drink
             3: Add Chips
             4: Checkout
             0: Exit

When selecting the add sandwich option a new interface will apprear: 

             1: Select bread
             2: Sandwich size
             3: Toppings
             4: Toast sandwich
             0: Exit
