### ISSUE TITLE
As a programmer, I want to see how the classes interact with one another and their individual components.

### ISSUE THREAD

**Issue by OmarD-Dev** [OmarD-Dev/FoodInspectorParadise#6]
A UML diagram will show how each class is related to one another and how they work within the application.

**Comment by ScripttKitty** [comment]
Our UML Diagram will show our classes, their relationships, and the type of class we chose them to be. We will be able to accomplish this using traditional UML signage.

**Comment by ScripttKitty** [comment]
Here is a rough draft that outlines our ideas for this project:

![Image](https://github.com/OmarD-Dev/FoodInspectorParadise/assets/89672262/49c48eb1-1d70-43be-94bf-cee2458526d6)
